orar/urls.py
"""orar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
"""
from django.contrib import admin, auth
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from usv_planificare.views.public import index

app_name = 'orar'

urlpatterns = [
    path('', index, name='index'),
    path('profil/', include('usv_auth.urls')),
    path('locatii/', include('usv_loc.urls')),
    path('structura/', include('usv_structura.urls')),
    path('orar/', include('usv_planificare.urls')),
    path('admin/', admin.site.urls),
    path(r'social/', include('social_django.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usv_structura/urls.py
from django.urls import path
from django.conf.urls import url
from dal import autocomplete

from . import views

app_name = 'usv_structura'

urlpatterns = [
    path('formatii/', views.index, name='listare'),
    path('formatii/stergere/<str:formatie>', views.stergere, name='stergere'),
    path('formatii/listare/<int:parinte>', views.list_elements, name='list_elements'),
    path('materii/', views.materii, name='materii'),
    path('materii/editare/<int:materie>', views.materii_edit, name='editare-materii'),
    path('materii/stergere/<int:materie>', views.materii_delete, name='stergere-materii'),
    url(r'materii/autocomplete/$',
        views.UsvUserAutocomplete.as_view(),
        name='materii-autocomplete'
       ),
]

usv_loc/models.py
from django.db import models

class Sala(models.Model):
    """Contine modelul pentru spatii de lucru

    Permite alegerea intre 4 tipuri de spatii de lucru. Fiecare spatiu are
    obligatoriu un corp si un nivel, reprezentate ca si campuri text. Se poate
    ulterior extinde catre structuri mai complexe (e.g. Corp, Nivel in obiecte
    separate).

    Attributes:
        corp: contine numele corpului
        nivel: contine, in mare parte, etajul
        nume: numerotarea salii
        destinatie: camp text, folosit pentru detalierea scopului
        tip: camp restrictionat la 4 valori (curs, laborator, birou sau altul)
        capacitate: numarul maxim de ocupanti
    """
    CURS, LAB, BIR, AUX = 'curs', 'lab', 'birou', 'aux'
    ALEGERI_LOCATIE  = (
        (CURS, 'Sală curs'),
        (LAB, 'Laborator'),
        (BIR, 'Birou'),
        (AUX, 'Altul'),
    )


    corp = models.CharField(max_length=40, blank=False)
    nivel = models.CharField(max_length=40, blank=False)
    nume = models.CharField(max_length=120, blank=False, unique=True)
    destinatie = models.TextField(max_length=1024, blank=True)
    tip = models.CharField(max_length=5, choices=ALEGERI_LOCATIE, default=LAB)
    capacitate = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        """Functie de afisare text a obiectului

        Folosita in mare parte la autocomplete. Returneaza corpul si numele
        salii
        """
        return self.corp + " / " + self.nume

    def natural_key(self):
        """Serializare JSON
        """
        return ({'corp':self.corp, 'nume': self.nume, 'nivel':self.nivel,
                 'tip':self.tip})

usv_structura/models.py
from django.db import models
from django.db.models.functions import Concat
from django.core.exceptions import ValidationError
from usv_auth.models import UsvUser

class Materie(models.Model):
    """Modelul pentru materii

    Avand in vedere ca trebuie sa avem programare de restante, recuperari si
    alte situatii speciale, modelul contine relatii cu structurile de
    profesori (nu si cu formatii de studiu).

    Avantajul este ca materiile si formatiile de studiu sunt independente, si
    pot fi schimbate de la an la an fara a face modificari in materii.

    Attributes:
        nume: numele materiei
        prescurtare: prescurtarea materiei, pentru afisare in calendar
        profesori: relatie de tip many to many catre tabelul de utilizatori
    """
    nume = models.CharField(max_length=90)
    prescurtare = models.CharField(max_length=20)
    profesori = models.ManyToManyField(UsvUser, related_name='materii')

    class Meta:
        ordering = ['nume']

    def __str__(self):
        """Functie de afisare text a obiectului

        Folosita in mare parte la autocomplete. Returneaza corpul si numele
        salii
        """
        return self.nume+ " (" + self.prescurtare+  ")"

    def natural_key(self):
        """Functie Django folosita pentru serializarea obiectelor care contin
        obiecte de tip Materie
        """
        return ({'nume':self.nume, 'prescurtare':self.prescurtare})


class Formatie(models.Model):
    """Contine modelul pentru formatii de studiu

    Modelul foloseste o structura de tip arbore pentru a stoca informatiile,
    care sunt de 3 tipuri (facultate, specializare, grupa). Formatiile copii
    (specializare, grupa) cer obligatoriu un parinte (foreign key catre self).

    Attributes:
        nume: contine numele formatii de studiu
        tip: camp restrictionat la 4 valori (facultate, specializare, grupa)
        parinte: foreign key catre self
        group_id: tine cheia structurii, folosit in ordonare

    TODO: ineficient dpdv spatiu, dar rapid pentru lookups, se poate
    tranzitiona la un model MPTT (modified preorder field traversal)
    """
    FAC, SPE, GRP = 'facultate', 'specializare', 'grupa'
    ALEGERI_FORMATIE = (
        (FAC, 'Facultate'),
        (SPE, 'Specializare'),
        (GRP, 'Grupă'),
    )

    nume = models.CharField(max_length=90, blank=False)
    tip = models.CharField(max_length=12, choices=ALEGERI_FORMATIE, default=FAC)
    parinte = models.ForeignKey('self', blank=True, null=True,
                    on_delete=models.CASCADE, related_name='subformatii')
    group_id = models.IntegerField(default=None, null=True)

    def natural_key(self):
        """Functie Django folosita pentru serializare
        """
        if self.parinte.parinte:
            return ({'tip':self.tip, 'nume':self.parinte.parinte.nume+\
                    " / "+self.parinte.nume+" / "+self.nume})

        if self.parinte:
            return ({'tip':self.tip, 'nume':self.parinte.nume+\
                    " / "+self.nume})

        return self.nume

    def clean(self):
        """Functie ce aplica criteriile custom de validare.

        Daca obiectul nu are parinte, trebuie sa fie de tip facultate.
        Daca obiectul are parinte, trebuie sa fie de tip specializare sau
        grupa.
        Nu exista parinte de tip grupa.
        """

        if self.tip == 'facultate' and self.parinte is not None:
            raise ValidationError({'tip': 'Facultățile nu permit atribut părinte definit'})

        if self.tip == 'specializare':
            # validam facultatea
            fac = None
            if Formatie.objects.filter(pk=self.parinte_id).exists():
                fac = Formatie.objects.get(pk=self.parinte_id)

            if not fac or (fac and fac.tip != 'facultate'):
                raise ValidationError({'tip': 'Specializările trebuie să aibă atribut părinte de tip facultate.'})

        if self.tip == 'grupa':
            # validam specializare 
            spec = None
            if Formatie.objects.filter(pk=self.parinte_id).exists():
                spec = Formatie.objects.get(pk=self.parinte_id)

            if not spec or (spec and spec.tip != 'specializare'):
                raise ValidationError({'tip': 'Grupele trebuie să aibă atribut părinte de tip specializare.'})


    def children(self):
        """Metoda folosita pentru a aduce elementele de tip frunza din cadrul
        unui element superior
        """

        return Formatie.objects.filter(parinte=self.pk)


    def update_group(self):
        """Functie folosita dupa salvarea modelului.

        Daca elementul este parinte (root), seteaza grupul echivalent cu
        primary key. Daca elementul este frunza, seteaza grupul, echivalent cu
        primary key-ul facultatii (root).
        """
        if self.parinte is None:
            self.group_id = self.pk
        else:
            if self.parinte.tip == 'specializare':
                self.group_id = self.parinte.parinte.pk
            else:
                self.group_id = self.parinte.pk

        return self

    def __str__(self):
        """Metoda pentru afisarea obiectului sub forma de string

        Se foloseste la afisarea dropdownului de formatii de studiu. Adauga
        separator (non blank space character, nu spatiu) in fata elementelor
        frunza.
        """
        sep = ''
        if self.tip == 'facultate':
            return self.nume

        if self.tip == 'specializare':
            return self.parinte.nume + " / " + self.nume

        return self.parinte.parinte.nume + " / " + self.parinte.nume +\
                " / " + self.nume

    def anotare():
        """Functie ce creeaza un camp suplimentar, ce afiseaza structura de
        intreaga a formatiei de studiu.

        Foloseste Expression language al ORM-ul Django (forma avansata), si se
        foloseste impreuna cu annotate().
        A durat ceva pana m-am prins :-)

        Examples:
            FIESC / SIC an 1 / Grupa 3711a
            FIESC / SIC an 2
            FIESC
        """
        return models.Case(
            models.When(tip=Formatie.SPE, then=Concat(
                models.F('parinte__nume'),
                models.Value(' / '),
                models.F('nume')
            )),
            models.When(tip=Formatie.GRP, then=Concat(
                models.F('parinte__parinte__nume'),
                models.Value(' / '),
                models.F('parinte__nume'),
                models.Value(' / '),
                models.F('nume')
            )),
            default=models.F('nume')
        )

usv_structura/forms.py
from django.forms import ModelForm, ValidationError, ModelChoiceField
from dal import autocomplete

from .models import Formatie, Materie

class MaterieForm(ModelForm):
    """Formularul pentru materii

    Permite adaugarea unor materii noi, editarea lor si relationarea cu modele
    de tip user.
    """

    class Meta:
        model = Materie
        fields = ['nume', 'prescurtare', 'profesori']
        widgets = {
            'profesori':
            autocomplete.ModelSelect2Multiple(url='usv_structura:materii-autocomplete')
        }


class FormatieForm(ModelForm):
    """Formularul pentru formatii de studiu

    Permite adaugarea unor formatii de studiu precizand urmatorii parametrii.

    Attributes:
        nume: numele formatiei de studiu
        tip: tipul formatiei de studiu (facultate, specializare, grupa)
        parinte: nodul parinte (e.g. facultate sau specializare)
    """

    class Meta:
        model = Formatie
        fields = ['nume', 'tip', 'parinte']


    # sortarea se face dupa group_id (parinte sau root), tip si nume ascendent,
    # ceea ce rezulta intr-o structura constanta pentru facultati si
    # specializari, fara a folosi coloane suplimentare pozitionale sau raw SQL
    # queries pentru join, sortare si agregare
    parinte = ModelChoiceField(
        required=False,
        label='Părinte',
        queryset=Formatie.objects.exclude(tip='grupa')
            .order_by('group_id', 'tip', 'nume')
    )

usv_structura/views.py
import os

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages

from dal import autocomplete

from .forms import FormatieForm, MaterieForm
from .models import Formatie, Materie

from usv_auth.models import UsvUser

@login_required
@staff_member_required
def index(request, stergere=None):
    """View general pentru formatii

    Formatiile se pot afisa cu toate formularele pe o singura pagina, pentru a
    reduce complexitatea. Se creeaza un singur view, unde in functie de
    parametrii si metoda HTTP, se aleg diferite operatii:
    * listare
    * adaugare
    """

    # sortarea se face dupa group_id (parinte sau root), tip si nume ascendent,
    # ceea ce rezulta intr-o structura constanta pentru facultati si
    # specializari, fara a folosi coloane suplimentare pozitionale sau raw SQL
    # queries pentru join, sortare si agregare
    context = {
        'formatii': Formatie.objects.filter(tip='facultate').order_by('nume')
            # .order_by('group_id', 'subgroup_nume', '-tip', 'nume'),
    }

    if request.method == 'POST':
        form = FormatieForm(request.POST)

        if form.is_valid():
            formatie = form.save()
            formatie.update_group().save()

            messages.add_message(request, messages.INFO,
                'Formație de studiu adăugată cu succes.')
            return redirect('usv_structura:listare')
    else:
        form = FormatieForm()

    context['form'] = form
    return render(request, os.path.join('formatii', 'listare.html'), context)

@login_required
@staff_member_required
def stergere(request, formatie=None):
    """View pentru stergere formatii de studiu 

    Face redirect la pagina de listare.

    Args:
        formatie: id-ul pentru care se doreste stergerea
    """

    formatie = Formatie.objects.get(pk=formatie)
    if formatie.children().count() != 0:
        messages.add_message(request, messages.ERROR,
            'Nu se pot șterge formații de studiu cu sub-elemente. \
            Ștergeți mai întăi sub-elementele și încercați din nou')
        return redirect('usv_structura:listare')
    formatie.delete()
    messages.add_message(request, messages.INFO,
        'Formație de studiu ștearsă cu succes.')

    return redirect('usv_structura:listare')

@login_required
def list_elements(request, parinte=None):
    """Functie ce returneaza specializari sau grupe in functie de parinte.

    Folosit pentru JavaScript asincron, in pagina de listare formatii de
    studiu.

    Args:
        parinte: cheia primara a parintelui, corespunde cu atributul parinte_id
            al copiilor
    """
    context = {
        'formatii' :Formatie.objects.filter(
            parinte_id=parinte
        ).order_by('nume')
    }

    return render(request, os.path.join('formatii', 'listare_js.html'), context)
    return JsonResponse(q, safe=False)


@login_required
@staff_member_required
def materii(request):
    context = {
        'materii': Materie.objects.prefetch_related('profesori')
    }

    if request.method == 'POST':
        form = MaterieForm(request.POST)

        if form.is_valid():
            materie = form.save()

            messages.add_message(request, messages.INFO,
                'Materie adăugată cu succes.')

            return redirect('usv_structura:materii')
    else:
        form = MaterieForm()

    context['form'] = form
    return render(request, os.path.join('materii', 'listare.html'), context)

@login_required
@staff_member_required
def materii_edit(request, materie=None):
    materie_instance = Materie.objects.get(pk=materie)
    context = {}

    if request.method == 'POST':
        form = MaterieForm(request.POST, instance=materie_instance)

        if form.is_valid():
            materie_instance = form.save()

            messages.add_message(request, messages.INFO,
                'Materie modificată cu succes.')

            return redirect('usv_structura:materii')
    else:
        form = MaterieForm(instance=materie_instance)

    context['form'] = form
    context['edit'] = materie is not None
    return render(request, os.path.join('materii', 'editare.html'), context)

@login_required
@staff_member_required
def materii_delete(request, materie=None):
    """View pentru stergere materii

    Face redirect la pagina de listare.

    Args:
        materie: id-ul pentru care se doreste stergerea
    """

    materie = Materie.objects.get(pk=materie)
    materie.delete()
    messages.add_message(request, messages.INFO,
        'Materia a fost ștearsă cu succes.')

    return redirect('usv_structura:materii')

class UsvUserAutocomplete(autocomplete.Select2QuerySetView):
    """Clasa ajutatoare pentru autocomplete ManyToMany

    Cauta obiecte de tip UsvUser, unde relatia User contine textul dat in input
    in campurile first_name si last_name.
    """
    def get_queryset(self):
        qs = UsvUser.objects.all()

        if self.q:
            qs = qs.filter(user__first_name__icontains=self.q) | qs.filter(user__last_name__icontains=self.q)

        return qs

usv_structura/templates/formatii/adaugare.html
{% extends "base.html" %}
{% block main %}

<div>
  <div class="card">
    {% if edit %}
    <h5 class="card-header">Editare locație</h5>
    {% else %}
    <h5 class="card-header">Adăugare locație</h5>
    {% endif %}
    <div class="card-body">
      <form class="form-signin" method="post" novalidate>
        {% csrf_token %}
        {% include "_form-single.html" %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Salvează</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extra %}
<script type="text/javascript">
  $(document).ready(function () {
    // monitorizam evenimente de tip schimbare, daca coincid cu selectarea campului de adaugare
    // transformam campul select intr-un camp de tip text
    monitorChange = function () {
      if ($(this).val() == 'add') {
        selectToText($(this));
      }
    }

    // functie de transformare select -> text
    selectToText = function (target) {
      target.parent().html('<input class="form-control" name="'+target.prop('name')+'" type="text" value="" />');
    }

    // daca nu exista corpuri, transformam direct
    // daca exista, atasam eveniment de monitorizare
    if ($('#id_corp option').length == 1) {
      selectToText($('#id_corp'));
    } else {
      $('#id_corp').change(monitorChange);
    }

    // daca nu exista nivele, transformam direct
    // daca exista, atasam eveniment de monitorizare
    if ($('#id_nivel option').length == 1) {
      selectToText($('#id_nivel'));
    } else {
      $('#id_nivel').change(monitorChange);
    }
  });
</script>
{% endblock %}

usv_structura/templates/formatii/listare.html
{% extends "base.html" %}
{% block main %}
<div>
  <div class="card">
    <h5 class="card-header">Adăugare formații de studiu</h5>
    <div class="card-body">
      <form class="form-signin" method="post" novalidate>
        {% csrf_token %}
        {% include "_form-single.html" %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Salvează</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <br/><br/>
  <div class="card">
    <h5 class="card-header">Listare formații de studiu</h5>
    <div class="card-body">
      {% if formatii.count %}
      <table class="table align-items-center">
        <thead class="thead-dark">
          <tr>
            <th scope="col" class="col-10">Nume</th>
            <th scope="col" class="col-sm-1 d-none d-sm-table-cell text-center">Tip</th>
            <th scope="col" class="col-2 col-sm-1 text-center">Acțiuni</th>
          </tr>
        </thead>
        <tbody>
          {% for formatie in formatii %}
          <tr class="table-info" data-fid="{{ formatie.pk }}">
            <td class="col-10">
              <i onClick="expandFormatie(this)" data-feather="plus-circle"></i>
              <strong>
                {{ formatie.nume }}
              </strong></td>
            <td class="col-sm-1 d-none d-sm-table-cell text-center">{{ formatie.get_tip_display }}</td>
            <td class="col-2 col-sm-1 text-center">
              <div class="btn-group" role="group">
                <a href="{% url 'usv_structura:stergere' formatie.pk %}">
                  <button type="button" class="btn btn-danger btn-sm">
                    <i data-feather="delete"></i>
                  </button>
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <div class="alert alert-warning" role="alert">
        Nu s-au găsit formații de studiu definite în acest program.
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}
{% block extra %}
<script type="text/javascript">
  $(document).ready(function () {
    expandFormatie = function (el) {
      // salvam stare initiala
      if (typeof(el.dataset.oldfeather) == 'undefined')
        el.dataset.oldfeather = 'plus-circle';

      // facem toggle la semne in functie de stare
      if (el.dataset.oldfeather  == 'plus-circle') {
        // trebuie expandat
        el.dataset.feather = el.dataset.oldfeather = 'minus-circle';
        // adaugam continutul intr-un tr nou, alaturat parintelui
        getFormatie($(el).parent().parent());
      } else {
        // trebuie minimizat
        el.dataset.feather = el.dataset.oldfeather = 'plus-circle';
        // stergem tr alaturat
        minimizeFormatie($(el).parent().parent());
      }

      feather.replace();
    }

    getFormatie = function (parinteTr) {
      $.get("/structura/formatii/listare/"+parinteTr.data('fid'), function (data, status) {
        parinteTr.after('<tr><td colspan="100" class="p-0 m-0"></td></tr>');
        // jQuery, plin de buguri din 2006 :-)
        target = parinteTr.next().get(0).children[0].innerHTML = data;
        // refreshuim iconurile
        feather.replace()
      });
    }
    minimizeFormatie = function (parinteTr) {
        parinteTr.next().remove();
    }
  });
</script>
{% endblock %}

usv_structura/templates/formatii/listare_js.html
<table class="table table-sm col-12 m-0">
  <tbody>
    {% for formatie in formatii %}
    {% if formatie.tip ==  'specializare' %}
    <tr data-fid="{{ formatie.pk }}" class="table-light">
      <td class="col-10 pl-4">
        <i onClick="expandFormatie(this)" data-feather="plus-circle"></i>
        <strong>
          {{ formatie.nume }}
        </strong>
      </td>
      {% else %}
      <tr data-fid="{{ formatie.pk }}">
        <td class="col-10 pl-4">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          {{ formatie.nume }}
        </td>
        {% endif %}
        <td class="col-sm-1 d-none d-sm-table-cell text-center">{{ formatie.get_tip_display }}</td>
        <td class="col-2 col-sm-1 text-center">
          <div class="btn-group" role="group">
            <a href="{% url 'usv_structura:stergere' formatie.pk %}">
              <button type="button" class="btn btn-danger btn-sm">
                <i data-feather="delete"></i>
              </button>
            </a>
          </div>
        </td>
      </tr>
      {% endfor %}
  </tbody>
</table>