orar/urls.py
"""orar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
"""
from django.contrib import admin, auth
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from usv_planificare.views.public import index

app_name = 'orar'

urlpatterns = [
    path('', index, name='index'),
    path('profil/', include('usv_auth.urls')),
    path('locatii/', include('usv_loc.urls')),
    path('structura/', include('usv_structura.urls')),
    path('orar/', include('usv_planificare.urls')),
    path('admin/', admin.site.urls),
    path(r'social/', include('social_django.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usv_loc/urls.py
from django.urls import path

from . import views

app_name = 'usv_loc'

urlpatterns = [
    path('', views.index, name='listare'),
    path('adaugare', views.adaugare, name='adaugare'),
    path('editare/<str:locatie>', views.adaugare, name='editare'),
    path('stergere/<str:locatie>', views.stergere, name='stergere'),
]

usv_loc/models.py
from django.db import models

class Sala(models.Model):
    """Contine modelul pentru spatii de lucru

    Permite alegerea intre 4 tipuri de spatii de lucru. Fiecare spatiu are
    obligatoriu un corp si un nivel, reprezentate ca si campuri text. Se poate
    ulterior extinde catre structuri mai complexe (e.g. Corp, Nivel in obiecte
    separate).

    Attributes:
        corp: contine numele corpului
        nivel: contine, in mare parte, etajul
        nume: numerotarea salii
        destinatie: camp text, folosit pentru detalierea scopului
        tip: camp restrictionat la 4 valori (curs, laborator, birou sau altul)
        capacitate: numarul maxim de ocupanti
    """
    CURS, LAB, BIR, AUX = 'curs', 'lab', 'birou', 'aux'
    ALEGERI_LOCATIE  = (
        (CURS, 'Sală curs'),
        (LAB, 'Laborator'),
        (BIR, 'Birou'),
        (AUX, 'Altul'),
    )


    corp = models.CharField(max_length=40, blank=False)
    nivel = models.CharField(max_length=40, blank=False)
    nume = models.CharField(max_length=120, blank=False, unique=True)
    destinatie = models.TextField(max_length=1024, blank=True)
    tip = models.CharField(max_length=5, choices=ALEGERI_LOCATIE, default=LAB)
    capacitate = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        """Functie de afisare text a obiectului

        Folosita in mare parte la autocomplete. Returneaza corpul si numele
        salii
        """
        return self.corp + " / " + self.nume

    def natural_key(self):
        """Serializare JSON
        """
        return ({'corp':self.corp, 'nume': self.nume, 'nivel':self.nivel,
                 'tip':self.tip})

usv_loc/forms.py
from django.forms import ModelForm, ValidationError, ChoiceField

from .models import Sala

class ChoiceFieldNoValidation(ChoiceField):
    def validate(self, value):
        pass

class SalaForm(ModelForm):
    """Formularul pentru locatii

    Permite alegerea unor corpuri sau nivele deja existente, sau adaugarea unor
    superlocatii noi; opereaza pe un singur model (si un singur tabel).
    """

    class Meta:
        model = Sala
        fields = ['corp', 'nivel', 'nume', 'tip', 'destinatie', 'capacitate']


    """Constructor formular

    Populeaza campurile corp si nivel cu valorile existente deja in baza de
    date. Functia este asemanatoare unui autocomplete, fara complexitate
    adaugata.

    Tranzitia de la campul de select la input arbitrar (Adaugare **obiect**) se
    face in template, folosind JavaScript.

    Daca formul este bound (are date), si corpul sau nivelul nu corespund
    valorilor reale, adaugam inputul la selectie.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        corpuri = Sala.objects.values_list('corp','corp').distinct()
        nivele = Sala.objects.values_list('nivel','nivel').order_by('nivel').distinct()

        self.fields['corp'].choices = corpuri

        if self.is_bound:
            corp_tuple = (self.data['corp'], self.data['corp'])
            if corp_tuple not in corpuri:
                self.fields['corp'].choices.append(corp_tuple)
        self.fields['corp'].choices.append(('add', 'Adăugare corp'))
        self.fields['nivel'].choices = nivele
        if self.is_bound:
            nivel_tuple = (self.data['nivel'], self.data['nivel'])
            if nivel_tuple not in nivele:
                self.fields['nivel'].choices.append(nivel_tuple)
        self.fields['nivel'].choices.append(('add', 'Adăugare nivel'))

    # rescriem modul de prezentare al campului corp, folosind dropdown
    corp = ChoiceFieldNoValidation(
        label="Corp"
    )

    # rescriem modul de prezentare al campului nivel, folosind dropdown
    nivel = ChoiceFieldNoValidation(
        label="Nivel"
    )

usv_loc/views.py
import os
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages

from .forms import SalaForm
from .models import Sala

TEMPLATE_BASE = 'locatii/'

@login_required
@staff_member_required
def index(request):
    """View pentru afisarea locatiilor
    """
    context = {
        'locatii': Sala.objects.order_by('nume').all()
    }

    return render(request, os.path.join(TEMPLATE_BASE, 'listare.html'), context)

@login_required
@staff_member_required
def adaugare(request, locatie=None):
    """View pentru adaugare si editare locatii

    Face redirect la pagina de listare in cazuri de success.

    Args:
        locatie: numele salii pentru care se doreste stergerea
    """
    context = {
        'form': None
    }

    form = None
    sala = None
    if locatie:
        sala = Sala.objects.get(nume=locatie)

    if request.method == 'POST':
        form = SalaForm(request.POST, instance=sala)

        if form.is_valid():
            locatie = form.save()

            messages.add_message(request, messages.INFO,
                'Salvare locație reușită.')
            return redirect('usv_loc:listare')
    else:
        form = SalaForm(instance=sala)

    context['edit'] = locatie is not None
    context['form'] = form
    return render(request, os.path.join(TEMPLATE_BASE, 'adaugare.html'), context)


@login_required
@staff_member_required
def stergere(request, locatie=None):
    """View pentru stergere locatii

    Face redirect la pagina de listare.

    Args:
        locatie: numele salii pentru care se doreste stergerea
    """
    sala = Sala.objects.get(nume=locatie)
    sala.delete()

    messages.add_message(request, messages.INFO,
        'Locație ștearsă cu succes.')

    return redirect('usv_loc:listare')

usv_loc/templates/locatii/adaugare.html
{% extends "base.html" %}
{% block main %}

<div>
  <div class="card">
    {% if edit %}
    <h5 class="card-header">Editare locație</h5>
    {% else %}
    <h5 class="card-header">Adăugare locație</h5>
    {% endif %}
    <div class="card-body">
      <form class="form-signin" method="post" novalidate>
        {% csrf_token %}
        {% include "_form-single.html" %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Salvează</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extra %}
<script type="text/javascript">
  $(document).ready(function () {
    // monitorizam evenimente de tip schimbare, daca coincid cu selectarea campului de adaugare
    // transformam campul select intr-un camp de tip text
    monitorChange = function () {
      if ($(this).val() == 'add') {
        selectToText($(this));
      }
    }

    // functie de transformare select -> text
    selectToText = function (target) {
      target.parent().html('<input class="form-control" name="'+target.prop('name')+'" type="text" value="" />');
    }

    // daca nu exista corpuri, transformam direct
    // daca exista, atasam eveniment de monitorizare
    if ($('#id_corp option').length == 1) {
      selectToText($('#id_corp'));
    } else {
      $('#id_corp').change(monitorChange);
    }

    // daca nu exista nivele, transformam direct
    // daca exista, atasam eveniment de monitorizare
    if ($('#id_nivel option').length == 1) {
      selectToText($('#id_nivel'));
    } else {
      $('#id_nivel').change(monitorChange);
    }
  });
</script>
{% endblock %}

usv_loc/templates/locatii/listare.html
{% extends "base.html" %}
{% block main %}

<div>
  <h1>Listare spații lucru</h1>
  {% if locatii.count %}
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Corp</th>
        <th scope="col">Nivel</th>
        <th scope="col">Numerotare</th>
        <th scope="col">Scop</th>
        <th scope="col" class="text-center">Capacitate</th>
        <th scope="col" class="text-center">Acțiuni</th>
      </tr>
    </thead>
    <tbody>
      {% for sala in locatii %}
      <tr>
        <td>{{ sala.corp }}</td>
        <td>{{ sala.nivel }}</td>
        <td>{{ sala.nume }}</td>
        <td>{{ sala.get_tip_display }}</td>
        <td class="text-center">{{ sala.capacitate }}</td>
        <td class="text-center">
          <div class="btn-group" role="group">
            <a href="{% url 'usv_loc:editare' sala.nume %}">
              <button type="button" class="btn btn-warning"><i data-feather="edit"></i> Editare</button>
            </a>
            <a href="{% url 'usv_loc:stergere' sala.nume %}">
              <button type="button" class="btn btn-danger"><i data-feather="delete"></i> Ștergere</button>
            </a>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div class="alert alert-warning" role="alert">
    Nu s-au găsit săli, laboratoare, birouri sau alte spații definite în acest
    program.
  </div>
  {% endif %}
</div>
{% endblock %}