orar/urls.py
"""orar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
"""
from django.contrib import admin, auth
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from usv_planificare.views.public import index

app_name = 'orar'

urlpatterns = [
    path('', index, name='index'),
    path('profil/', include('usv_auth.urls')),
    path('locatii/', include('usv_loc.urls')),
    path('structura/', include('usv_structura.urls')),
    path('orar/', include('usv_planificare.urls')),
    path('admin/', admin.site.urls),
    path(r'social/', include('social_django.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usv_planificare/urls.py
from django.urls import path
from django.conf.urls import url

from .views import standard, autocomplete, public
from usv_structura.views import UsvUserAutocomplete

app_name = 'usv_planificare'

urlpatterns = [
    path('rezervare', standard.rezervare, name='rezervare'),
    path('rezervare/<int:rezervare>', standard.rezervare, name='edit-rezervare'),

    path('listare', standard.index, name='listare'),
    path('listare/<str:tip_obiect>', public.index, name='listare-public'),

    path('planificari.json', standard.json_planificari, name='json-planificari'),
    path('planificari/<str:mod>/<int:related_pk>.json', standard.json_planificari, name='json-planificari'),

    path('anulare/<int:rezervare>', standard.anulare, name='anulare'),

    url(r'autocomplete/materii/$',
        autocomplete.MaterieAutocomplete.as_view(),
        name='materii-ac'
       ),
    url(r'autocomplete/locatii/$',
        autocomplete.SalaAutocomplete.as_view(),
        name='locatii-ac'
       ),
    url(r'autocomplete/formatii/$',
        autocomplete.FormatieAutocomplete.as_view(),
        name='formatii-ac'
       ),
    url(r'autocomplete/profesori/$',
        UsvUserAutocomplete.as_view(),
        name='profesori-ac'
       ),
]

usv_structura/urls.py
from django.urls import path
from django.conf.urls import url
from dal import autocomplete

from . import views

app_name = 'usv_structura'

urlpatterns = [
    path('formatii/', views.index, name='listare'),
    path('formatii/stergere/<str:formatie>', views.stergere, name='stergere'),
    path('formatii/listare/<int:parinte>', views.list_elements, name='list_elements'),
    path('materii/', views.materii, name='materii'),
    path('materii/editare/<int:materie>', views.materii_edit, name='editare-materii'),
    path('materii/stergere/<int:materie>', views.materii_delete, name='stergere-materii'),
    url(r'materii/autocomplete/$',
        views.UsvUserAutocomplete.as_view(),
        name='materii-autocomplete'
       ),
]

usv_planificare/models.py
from django.db import models
from django.conf import settings

from usv_auth.models import UsvUser
from usv_structura.models import Materie, Formatie
from usv_loc.models import Sala 

class PlanSpecial(models.Model):
    """Clasa pentru planificari orare non-recurente

    Folosita pentru planificari de restante, recuperari, examene.

    Attributes:
        start_date: data de inceput
        end_date: data de sfarsit
        profesor: UsvUser atasat evenimentului
        tip: tip de eveniment, valori multiple
        sala: obiect Sala atasat evenimentului
        materie: obiect Materie atasat evenimentului
        formatii: formatii de studiu atasate evenimentului
        autor: UsvUser care creeaza evenimentul
        notite: camp text pentru comentarii
        descriere = camp text pentru descriere eveniment (si arhivare)
    """
    RES, REC_C, REC_L, REC_S, EXA, ALT = 'restanta', 'rec_c', 'rec_l', 'rec_s', 'examen', 'alt'

    ALEGERI_PLAN_SPEC = (
        (RES, 'Restanță'),
        (REC_C, 'Recuperare curs'),
        (REC_S, 'Recuperare seminar'),
        (REC_L, 'Recuperare laborator'),
        (EXA, 'Examen'),
        (ALT, 'Altul')
    )
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    profesor  = models.ForeignKey(UsvUser, on_delete=models.SET_NULL, null=True)
    autor = models.ForeignKey(UsvUser, on_delete=models.SET_NULL, null=True,
                              related_name='planuri')
    sala = models.ForeignKey(Sala, on_delete=models.SET_NULL, null=True)
    materie = models.ForeignKey(Materie, on_delete=models.SET_NULL, null=True)
    formatii = models.ManyToManyField(Formatie)
    tip = models.CharField(
        max_length=100,
        choices=ALEGERI_PLAN_SPEC,
        default=RES
    )
    notite = models.TextField(max_length=256, blank=True)
    descriere = models.TextField(max_length=4096)

    def set_notite(self):
        """Genereaza descriere

        Folosita la stocarea descrierii, pentru arhivare, in caz ca obiectele
        relationate sunt sterse sau dispar.
        """
        self.descriere = '''- Cadru didactic: {}

- Notite:
{}

- Locatie: {}

- Materie: {}

- Formatii de studiu:
    * {}
'''.format(
    self.profesor.user.get_full_name(),
    self.notite,
    self.sala,
    self.materie,
    "\n   *  ".join(str(o) for o in self.formatii.all())
)
        return self

usv_planificare/views/autocomplete.py
import os

from django.shortcuts import render, redirect
from django.db.models import F

from dal import autocomplete

from usv_structura.models import Materie, Formatie
from usv_loc.models import Sala


class SalaAutocomplete(autocomplete.Select2QuerySetView):
    """Clasa ajutatoare pentru autocomplete ManyToMany

    Cauta obiecte de tip Sala, unde numele sau corpul contin textul dat in input
    """
    def get_queryset(self):
        qs = Sala.objects.all()

        if self.q:
            qs = qs.filter(corp__icontains=self.q) | qs.filter(nume__icontains=self.q)

        return qs

class MaterieAutocomplete(autocomplete.Select2QuerySetView):
    """Clasa ajutatoare pentru autocomplete OneToMany

    Cauta obiecte de tip Materie, unde numele sau prescurtarea contin textul dat in input
    """
    def get_queryset(self):
        staff = self.request.user.is_staff or self.request.user.is_anonymous

        if staff:
            qs = Materie.objects.all()
            if self.q:
                qs = qs.filter(nume__icontains=self.q) | qs.filter(prescurtare__icontains=self.q)
        else:
            qs = Materie.objects.all()
            if self.q:
                qs = qs.filter(profesori__id=self.request.user.usvuser.pk) &\
                    (qs.filter(nume__icontains=self.q) |\
                     qs.filter(prescurtare__icontains=self.q))
            else:
                qs = qs.filter(profesori__id=self.request.user.usvuser.pk)

        return qs

class FormatieAutocomplete(autocomplete.Select2QuerySetView):
    """Clasa ajutatoare pentru autocomplete OneToMany

    Cauta obiecte de tip Formatie, unde numele sau prescurtarea contin textul dat in input
    """
    def get_queryset(self):
        qs = Formatie.objects.annotate(full_path=Formatie.anotare()).all()

        if self.q:
            qs = qs.filter(full_path__icontains=self.q).order_by('full_path')
                # qs.filter(parinte__nume__icontains=self.q) |\
                # qs.filter(nume__icontains=self.q)

        return qs

    def get_result_label(self, obj):
        return obj.full_path
        ret = ""
        if obj.tip == 'specializare':
            ret += obj.parinte.nume + " / "

        if obj.tip == 'grupa':
            ret += obj.parinte.parinte.nume + " / "  + obj.parinte.nume + " / "

        ret += obj.nume

        return ret

usv_planificare/views/public.py
# toate view-urile publice
import os

from django.contrib import messages
from django.shortcuts import render, redirect

from usv_planificare.forms import (
    AlegereSalaForm,
    AlegereMaterieForm,
    AlegereFormatieForm,
    AlegereProfesorForm
)

def index(request, tip_obiect=''):
    """View pentru afisare calendar pe sali
    """

    if tip_obiect not in ['profesor', 'sala', 'materie', 'formatii']:
        tip_obiect = 'sala'

    show_calendar = False
    id_obiect = 0

    if request.method == 'POST':
        form = formular_obiect(tip_obiect, request.POST)
        if form.is_valid():
            show_calendar = True
            id_obiect = form[tip_obiect].value
    else:
        form = formular_obiect(tip_obiect)

    context = {
        'form': form,
        'show_calendar': show_calendar,
        'tip_obiect': tip_obiect,
        'id_obiect': id_obiect
    }

    return render(request, os.path.join('rezervari', 'listare-public.html'),
                  context)

def formular_obiect(tip_obiect, post_data=None):
    if tip_obiect == 'sala':
        form = AlegereSalaForm(post_data)
    if tip_obiect == 'materie':
        form = AlegereMaterieForm(post_data)
    if tip_obiect == 'formatii':
        form = AlegereFormatieForm(post_data)
    if tip_obiect == 'profesor':
        form = AlegereProfesorForm(post_data)
    return form

usv_planificare/views/standard.py
import os
import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render, redirect

from usv_planificare.forms import PlanSpecialForm, PlanSpecialAdminForm
from usv_planificare.models import PlanSpecial

def json_planificari(request, mod='profesor', related_pk=None):
    """Functie de afisare (JSON) a planificarilor

    Folosita in toate paginile de afisare, interfatata cu fullcalendar.io

    Args:
        request: obiect de tip request
        mod: cautare filtrata pe un obiect de tip UsvUser, Materie, Formatie
            sau Sala
        related_pk: cheia asociata cu obiectul de mai sus
    Returns:
        Obiect de tip PlanSpecial serializat JSON
    """

    s_input = request.GET.get('start_date')
    if not s_input:
        start_date = datetime.datetime.fromtimestamp(0);
    else:
        start_date = datetime.datetime.fromtimestamp(int(s_input)/1000)

    e_input = request.GET.get('end_date')
    if not e_input:
        end_date = datetime.datetime.fromtimestamp(2147483647)
    else:
        end_date = datetime.datetime.fromtimestamp(int(e_input)/1000)

    if mod == 'profesor':
        if not related_pk and not request.user.is_anonymous:
            related_pk = request.user.usvuser.pk

    qs = json_mod(mod, start_date, end_date, related_pk)

    qs_json = serializers.serialize(
        'json',
        qs,
        use_natural_foreign_keys=True,
        fields=('start_date', 'end_date', 'tip', 'materie',\
                'descriere')
    )
    return HttpResponse(qs_json, content_type='application/json')

def json_mod(mod, start_date, end_date, rel):
    """Functie auxiliara pentru afisare JSON

    Aduce un obiect de tip QuerySet bazat pe PlanSpecial, in functie de
    mod si cheia specificata. Foloseste overloading de tip kwargs pe functia de
    filtru, folosind parametrul ``mod`` si valoarea din ``rel``.

    Args:
        mod: tipul de date cerut [profesor,sala,formatii,materie]
        start_date: datetime pentru limita inferioara
        end_date: datetime pentru limita superioara
        rel: cheia obiectului pe care pivotam

    Returns:
        Django QuerySet folosind managerul din ``mod``
    """
    qs = PlanSpecial.objects

    if mod not in ['profesor', 'sala', 'materie', 'formatii']:
        return qs.none()

    if start_date is not None and end_date is not None:
        if mod == 'formatii':
            qs = (qs.filter(**{mod+'__id': rel}) |\
                 qs.filter(**{mod+'__subformatii__id': rel}) |\
                 qs.filter(**{mod+'__subformatii__subformatii__id': rel})) & \
                    qs.filter(start_date__gte=start_date) & \
                    qs.filter(end_date__lte=end_date)
        else:
            qs = qs.filter(**{mod+'__id': rel}) & \
                    qs.filter(start_date__gte=start_date) & \
                    qs.filter(end_date__lte=end_date)
    else:
        qs = qs.filter(**{mod+'__id':rel})

    return qs.distinct()

@login_required
def index(request):
    """View pentru afisare calendar personal cu planificari de timp

    In cazul in care userul este standard sau administrator, se prezinta un alt
    ecran in care trebuie selectat profesorul (vezi Orar -> Cadre didactice). Daca
    userul este profesor, i se prezinta doar planificarile sale non-recurente.

    """

    return render(request, os.path.join('rezervari', 'listare-special.html'))

@login_required
def rezervare(request, rezervare=None):
    if request.user.is_staff:
        return rezervare_admin(request, rezervare)
    else:
        return rezervare_cadru(request, rezervare)

def rezervare_cadru(request, rezervare):
    """functie rezervare pentru profesori

    Nu lasa selectia campului de tip profesor, foloseste un modelform restrans.
    """
    if rezervare:
        rez_instance = PlanSpecial.objects.get(pk=rezervare)
    else:
        rez_instance = PlanSpecial()

    context = {}

    if request.method == 'POST':
        form = PlanSpecialForm(request.user.usvuser, request.POST, instance=rez_instance)

        if form.is_valid():
            rez_instance = form.save()
            rez_instance.autor = request.user.usvuser
            rez_instance.profesor = request.user.usvuser
            rez_instance.set_notite()
            rez_instance.save()

            messages.add_message(request, messages.INFO,
                'Rezervare salvată cu succes.')

            return redirect('usv_planificare:listare')
    else:
        form = PlanSpecialForm(request.user.usvuser, instance=rez_instance)

    context['form'] = form
    context['edit'] = rezervare is not None
    return render(request, os.path.join('rezervari', 'editare.html'), context)

def rezervare_admin(request, rezervare):
    """functie rezervare pentru administratori

    Permite alegerea tuturor materiilor si a tuturor profesorilor
    """
    if rezervare:
        rez_instance = PlanSpecial.objects.get(pk=rezervare)
    else:
        rez_instance = PlanSpecial()

    context = {}

    if request.method == 'POST':
        form = PlanSpecialAdminForm(request.user.usvuser, request.POST, instance=rez_instance)

        if form.is_valid():
            rez_instance = form.save()
            rez_instance.autor = request.user.usvuser
            rez_instance.set_notite()
            rez_instance.save()

            messages.add_message(request, messages.INFO,
                'Rezervare salvată cu succes.')

            return redirect('usv_planificare:listare')
    else:
        form = PlanSpecialAdminForm(request.user.usvuser, instance=rez_instance)

    context['form'] = form
    context['edit'] = rezervare is not None
    return render(request, os.path.join('rezervari', 'editare.html'), context)

@login_required
def anulare(request, rezervare=None):
    """View pentru stergere materii

    Face redirect la pagina de listare.

    Args:
        materie: id-ul pentru care se doreste stergerea
    """
    rezervare = PlanSpecial.objects.get(pk=rezervare)
    if (not request.user.is_staff) and (request.user.usvuser.pk != rezervare.profesor.pk):
        messages.add_message(request, messages.ERROR,
            'Nu se pot anula rezervări de timp pentru alte cadre didactice.\
                             Contactați un administrator.')
        return redirect('usv_planificare:listare')

    if datetime.datetime.now(datetime.timezone.utc) > rezervare.start_date:
        messages.add_message(request, messages.ERROR,
            'Nu se pot anula rezervări de timp pentru evenimente din trecut.')
        return redirect('usv_planificare:listare')

    rezervare.delete()
    messages.add_message(request, messages.INFO,
            'Rezervarea a fost anulată cu succes.')

    return redirect('usv_planificare:listare')

usv_planificare/templates/rezervari/_calendar.html
{% load static %}
<script type="text/javascript" src="{% static 'fullcalendar/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fullcalendar/fullcalendar.min.js'%}"></script>
<script type="text/javascript" src="{% static 'fullcalendar/ro.js'%}"></script>
<script type="text/javascript" src="{% static 'qtip/jquery.qtip.min.js'%}"></script>
<script type="text/javascript" src="{% static 'orar/calendar.js'%}"></script>
<link rel="stylesheet" href="{% static 'fullcalendar/fullcalendar.min.css' %}" />
<link rel="stylesheet" href="{% static 'qtip/jquery.qtip.min.css' %}" />

usv_planificare/templates/rezervari/adaugare.html
<div class="card">
  {% if edit %}
  <h5 class="card-header">Modificare rezervare sală</h5>
  {% else %}
  <h5 class="card-header">Rezervare sală</h5>
  {% endif %}
  <div class="card-body">
    {% if not user.is_staff %}
    <p class="note">Formularul curent vă permite să selectați una dintre materiile unde ați fost desemnat ca și cadru didactic, în vederea rezervării unei săli sau locații pentru orice sitație specială (restanța, recuperare, examen sau altele)..</p>
    {% endif %}
    <form class="form-signin" method="post" novalidate>
      {% csrf_token %}
      {% include "_form-single.html" %}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button class="btn btn-lg btn-primary btn-block" type="submit">Salvează</button>
        </div>
      </div>
    </form>
  </div>
</div>

usv_planificare/templates/rezervari/detaliu_formatii.html
{% with form.obiect as formatie %}
<div class="card">
  <h5 class="card-header">Detaliu selecție</h5>
  <div class="card-body">
    <dl>
      <dt>Nume</dt>
      <dd>{{ formatie }}</dd>
      <dt>Tip</dt>
      <dd>{{ formatie.get_tip_display }}</dd>
    </dl>
  </div>
</div>
<hr>
{% endwith %}

usv_planificare/templates/rezervari/detaliu_materie.html
{% with form.obiect as materie %}
<div class="card">
  <h5 class="card-header">Detaliu selecție</h5>
  <div class="card-body">
    <dl>
      <dt>Nume</dt>
      <dd>{{ materie.nume }}</dd>
      <dt>Prescurtare</dt>
      <dd>{{ materie.prescurtare }}</dd>
      <dt>Profesori asociați</dt>
      <dd>{{ materie.profesori.all|join:"; " }}</dd>
    </dl>
  </div>
</div>
<hr>
{% endwith %}

usv_planificare/templates/rezervari/detaliu_profesor.html
{% with form.obiect as profesor %}
<div class="card">
  <h5 class="card-header">Detaliu selecție</h5>
  <div class="card-body">
    <dl>
      <dt>Titlu</dt>
      <dd>{{ profesor.titlu}}</dd>
      <dt>Nume complet</dt>
      <dd>{{ profesor }}</dd>
      <dt>Adresă</dt>
      <dd>{{ profesor.adresa }}</dd>
      <dt>Telefon</dt>
      <dd>{{ profesor.telefon }}</dd>
      <dt>Pagină web</dt>
      <dd>{{ profesor.homepage }}</dd>
    </dl>
  </div>
</div>
<hr>
{% endwith %}

usv_planificare/templates/rezervari/detaliu_sala.html
{% with form.obiect as sala %}
<div class="card">
  <h5 class="card-header">Detaliu selecție</h5>
  <div class="card-body">
    <dl>
      <dt>Numerotare</dt>
      <dd>{{ sala.nume }}</dd>
      <dt>Corp</dt>
      <dd>{{ sala.corp}}</dd>
      <dt>Nivel</dt>
      <dd>{{ sala.nivel }}</dd>
      <dt>Capacitate</dt>
      <dd>{{ sala.capacitate }}</dd>
      <dt>Destinație</dt>
      <dd>{{ sala.destinatie}}</dd>
    </dl>
  </div>
</div>
<hr>
{% endwith %}

usv_planificare/templates/rezervari/editare.html
{% extends "base.html" %}
{% load static %}
{% block main %}
{% include 'rezervari/adaugare.html' %}
{% endblock %}
{% block extra %}
{{ form.media }}
<script type="text/javascript" src={% static '/pickadate/picker.js' %}></script>
<script type="text/javascript" src={% static '/pickadate/picker.date.js' %}></script>
<script type="text/javascript" src={% static '/pickadate/picker.time.js' %}></script>
<script type="text/javascript" src={% static '/pickadate/translations/ro_RO.js' %}></script>

<script type="text/javascript">
  $(document).ready(function () {
    // fix pt django date-value
    $('#id_start_date_0').attr('data-value', $('#id_start_date_0').val());
    $('#id_start_date_0').pickadate({
      formatSubmit: 'yyyy-mm-dd',
      hiddenName: true
    });
    $('#id_start_date_1').pickatime({
      formatSubmit: 'HH:i',
      format: 'HH:i',
      hiddenName: true
    });
  });
</script>
<link rel="stylesheet" type="text/css" href="{% static '/pickadate/themes/default.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static '/pickadate/themes/default.time.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static '/pickadate/themes/default.date.css' %}" />
{% endblock %}

usv_planificare/templates/rezervari/listare-public.html
{% extends "base.html" %}
{% load static %}
{% block main %}

<div>
  {% if show_calendar %}
  {% with 'rezervari/detaliu_'|add:tip_obiect|add:'.html' as tpl_detaliu %}
  {% include tpl_detaliu %}
  {% endwith %}
  <div class="card">
    <h5 class="card-header">Listare planificări pentru: {{ form.nume }}</h5>
    <div class="card-body">
      <div id="calendar">
      </div>
    </div>
  </div>
  {% else %}
  <div class="card">
    <h5 class="card-header">Afișare program pentru:</h5>
    <div class="card-body">
      <form class="form-signin" method="post" novalidate>
        {% csrf_token %}
        {% include "_form-single.html" %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Caută</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}
{% block extra %}
{% if show_calendar %}
{% include 'rezervari/_calendar.html' %}
<script type="text/javascript">
  calendarUrl = "/orar/planificari/{{ tip_obiect }}/{{ id_obiect }}.json";
{% if not user.is_anonymous %}
is_admin = true;
{% else %}
is_admin = false;
{% endif %}
</script>
{% else %}
{{ form.media }}
{% endif %}

{% endblock %}

usv_planificare/templates/rezervari/listare-special.html
{% extends "base.html" %}
{% load static %}
{% block main %}

<div>
  <div class="card">
    <h5 class="card-header">Listare planificări</h5>
    <div class="card-body">
      <div id="calendar">
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block extra %}
<script type="text/javascript" src="{% static 'fullcalendar/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fullcalendar/fullcalendar.min.js'%}"></script>
<script type="text/javascript" src="{% static 'fullcalendar/ro.js'%}"></script>
<script type="text/javascript" src="{% static 'qtip/jquery.qtip.min.js'%}"></script>
<script type="text/javascript" src="{% static 'orar/calendar.js'%}"></script>
<link rel="stylesheet" href="{% static 'fullcalendar/fullcalendar.min.css' %}" />
<link rel="stylesheet" href="{% static 'qtip/jquery.qtip.min.css' %}" />

{% if not user.is_anonymous %}
<script type="text/javascript">
calendarUrl = "/orar/planificari.json";
is_admin = true
</script>
{% endif %}
{% endblock %}

usv_planificare/templates/rezervari/listare.html
{% extends "base.html" %}
{% block main %}

<div>
  {% include 'materii/adaugare.html' with form=form edit=edit %}
  <br/><br/>
  <div class="card">
    <h5 class="card-header">Listare materii</h5>
    <div class="card-body">
      {% if materii.count %}
      <table class="table align-items-center">
        <thead class="thead-dark">
          <tr>
            <th scope="col" class="col-6">Nume</th>
            <th scope="col" class="col-4 d-none d-sm-table-cell">Profesori</th>
            <th scope="col" class="col-4 col-sm-2 text-center">Acțiuni</th>
          </tr>
        </thead>
        <tbody>
          {% for materie in materii %}
          <tr>
            <td class="col-6">
                {{ materie.nume }}
            </td>
            <td class="col-4 d-none d-sm-table-cell">
              {% with materie.profesori.all as profesori %}
              {% if profesori.count %}
              {% for profesor in profesori %}
              {{ profesor.user.last_name }}, {{ profesor.user.first_name }}<br/>
              {% endfor %}
              {% else %}
                Nu există
              {% endif %}
              {% endwith %}
            </td>
            <td class="col-4 col-sm-2 text-center">
              <div class="btn-group" role="group">
                <a href="{% url 'usv_structura:editare-materii' materie.pk %}">
                  <button type="button" class="btn btn-warning btn-sm">
                    <i data-feather="edit"></i> <span class="d-none d-block-md">Editare</span>
                  </button>
                </a>
                <a href="{% url 'usv_structura:stergere-materii' materie.pk %}">
                  <button type="button" class="btn btn-danger btn-sm">
                    <i data-feather="delete"></i> <span class="d-none d-block-md">Stergere</span>
                  </button>
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <div class="alert alert-warning" role="alert">
        Nu s-au găsit materii definite în acest program.
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}
{% block extra %}
{{ form.media }}
{% endblock %}