orar/urls.py
"""orar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
"""
from django.contrib import admin, auth
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from usv_planificare.views.public import index

app_name = 'orar'

urlpatterns = [
    path('', index, name='index'),
    path('profil/', include('usv_auth.urls')),
    path('locatii/', include('usv_loc.urls')),
    path('structura/', include('usv_structura.urls')),
    path('orar/', include('usv_planificare.urls')),
    path('admin/', admin.site.urls),
    path(r'social/', include('social_django.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usv_auth/urls.py
from django.urls import path

from . import views

app_name = 'usv_auth'

urlpatterns = [
    path('', views.index, name='profil'),
    path('adaugare', views.adaugare, name='adaugare'),
    path('editare/<str:username>', views.adaugare, name='editare'),
    path('stergere/<str:username>', views.stergere, name='stergere'),
    path('listare', views.listare, name='listare')
]

usv_loc/urls.py
from django.urls import path

from . import views

app_name = 'usv_loc'

urlpatterns = [
    path('', views.index, name='listare'),
    path('adaugare', views.adaugare, name='adaugare'),
    path('editare/<str:locatie>', views.adaugare, name='editare'),
    path('stergere/<str:locatie>', views.stergere, name='stergere'),
]

usv_planificare/urls.py
from django.urls import path
from django.conf.urls import url

from .views import standard, autocomplete, public
from usv_structura.views import UsvUserAutocomplete

app_name = 'usv_planificare'

urlpatterns = [
    path('rezervare', standard.rezervare, name='rezervare'),
    path('rezervare/<int:rezervare>', standard.rezervare, name='edit-rezervare'),

    path('listare', standard.index, name='listare'),
    path('listare/<str:tip_obiect>', public.index, name='listare-public'),

    path('planificari.json', standard.json_planificari, name='json-planificari'),
    path('planificari/<str:mod>/<int:related_pk>.json', standard.json_planificari, name='json-planificari'),

    path('anulare/<int:rezervare>', standard.anulare, name='anulare'),

    url(r'autocomplete/materii/$',
        autocomplete.MaterieAutocomplete.as_view(),
        name='materii-ac'
       ),
    url(r'autocomplete/locatii/$',
        autocomplete.SalaAutocomplete.as_view(),
        name='locatii-ac'
       ),
    url(r'autocomplete/formatii/$',
        autocomplete.FormatieAutocomplete.as_view(),
        name='formatii-ac'
       ),
    url(r'autocomplete/profesori/$',
        UsvUserAutocomplete.as_view(),
        name='profesori-ac'
       ),
]

usv_structura/urls.py
from django.urls import path
from django.conf.urls import url
from dal import autocomplete

from . import views

app_name = 'usv_structura'

urlpatterns = [
    path('formatii/', views.index, name='listare'),
    path('formatii/stergere/<str:formatie>', views.stergere, name='stergere'),
    path('formatii/listare/<int:parinte>', views.list_elements, name='list_elements'),
    path('materii/', views.materii, name='materii'),
    path('materii/editare/<int:materie>', views.materii_edit, name='editare-materii'),
    path('materii/stergere/<int:materie>', views.materii_delete, name='stergere-materii'),
    url(r'materii/autocomplete/$',
        views.UsvUserAutocomplete.as_view(),
        name='materii-autocomplete'
       ),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Marina Popeanu, Ioana Mihoc, Ciprian Stavovei, Sebastian Traian Măcărescu, Octav Opaschi">

    <title>USV Orar - MICSO</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="shortcut icon" href="{%  static 'assets/favicon.ico' %}">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow d-print-none">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Orar USV</a>
      <ul class="navbar-nav flex-row px-3 mr-auto d-sm-block d-md-none">
        <li class="nav-item">
          <a class="nav-link" data-toggle="collapse" role="button" aria-expanded="false" href="#collapsable" aria-controls="collapsable"><span data-feather="menu"></span> Meniu</a>
        </li>
      </ul>
      <ul class="navbar-nav flex-row px-3">
        <li class="nav-item">
          {% if user.is_anonymous %}
          <a class="nav-link" href="/accounts/login">Autentificare</a>
          {% else %}
          <a class="nav-link" href="/accounts/logout?next=/">Ieșire</a>
          {% endif %}
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row mt-4">
        <nav class="col-12 col-md-2 d-md-block bg-light sidebar collapse mt-4 mt-md-0 d-print-none" id="collapsable">
          <div class="sidebar-sticky">
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Orar</span>
              <a class="d-flex align-items-center text-muted" href="#">
              </a>
            </h6>
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link " href="{% url 'usv_planificare:listare-public' tip_obiect='sala' %}">
                  <span data-feather="map"></span>
                  Săli
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'usv_planificare:listare-public' tip_obiect='profesor' %}">
                  <span data-feather="user"></span>
                  Cadre didactice
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'usv_planificare:listare-public' tip_obiect='materie' %}">
                  <span data-feather="book-open"></span>
                  Materii
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'usv_planificare:listare-public' tip_obiect='formatii' %}">
                  <span data-feather="globe"></span>
                  Formații de studiu
                </a>
              </li>
            </ul>
            {% if not user.is_anonymous %}
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Planificare</span>
              <a class="d-flex align-items-center text-muted" href="#">
              </a>
            </h6>
            <ul class="nav flex-column">
              {% if not user.is_anonymous and not user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'usv_planificare:listare' %}">
                  <span data-feather="calendar"></span>
                  Vizualizare program
                </a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'usv_planificare:rezervare' %}">
                  <span data-feather="bookmark"></span>
                  Rezervare sală
                </a>
              </li>
            </ul>
            {% endif %}

            {% if not user.is_anonymous and user.is_staff %}
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Funcții administrative</span>
              <a class="d-flex align-items-center text-muted" href="#">
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link disabled" href="#">
                  <span data-feather="map"></span>
                  Management locații
                </a>
                <ul class="nav flex-column">
                  <li class="nav-item pl-3">
                    <a class="nav-link" href="{% url 'usv_loc:adaugare' %}">
                      <span data-feather="chevron-right"></span>
                      Adăugare
                    </a>
                  </li>
                  <li class="nav-item pl-3">
                    <a class="nav-link" href="{% url 'usv_loc:listare' %}">
                      <span data-feather="chevron-right"></span>
                      Listare
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">
                  <span data-feather="grid"></span>
                  Structură facultăți
                </a>
                <ul class="nav flex-column">
                  <li class="nav-item pl-3">
                    <a class="nav-link" href="{% url 'usv_structura:materii' %}">
                      <span data-feather="chevron-right"></span>
                      Materii
                    </a>
                  </li>
                  <li class="nav-item pl-3">
                    <a class="nav-link" href="{% url 'usv_structura:listare' %}">
                      <span data-feather="chevron-right"></span>
                      Formații de studiu
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">
                  <span data-feather="users"></span>
                  Cadre didactice
                </a>
                <ul class="nav flex-column">
                  <li class="nav-item pl-3">
                    <a class="nav-link" href="{% url 'usv_auth:adaugare' %}">
                      <span data-feather="chevron-right"></span>
                      Adăugare
                    </a>
                  </li>
                  <li class="nav-item pl-3">
                    <a class="nav-link" href="{% url 'usv_auth:listare' %}">
                      <span data-feather="chevron-right"></span>
                      Listare
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          {% endif %}
        </nav>

        <main role="main" class="col-12 col-md-9 ml-sm-auto col-lg-10 px-4 mt-4 d-print-block">
        {% if messages %}
        <div class="messages">
          {% for message in messages %}
          <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
        </div>
        {% endif %}
        {% block main %}
        {% endblock %}
        <footer class="footer mt-2">
            <div class="row">
            <p class="text-right col-12 text-muted">Powered by <img src="{% static 'assets/echipa.png' %}" height="40px" title="Marina Popeanu, Ioana Mihoc, Ciprian Stavovei, Sebastian Traian Măcărescu, Octav Opaschi" alt="Marina Popeanu, Ioana Mihoc, Ciprian Stavovei, Sebastian Traian Măcărescu, Octav Opaschi"/></p>
            </div>
        </footer>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="{% static 'assets/js/vendor/jquery.min.js' %}"></script>
      <script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>

      <!-- Icons -->
      <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
      <script>
        feather.replace()
      </script>

      <!-- USV extra -->
      {% block extra %}
      {% endblock %}

  </body>
</html>